# Generated by Django 5.1.5 on 2025-02-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='actualizada',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(default='pendiente', max_length=10),
        ),
    ]
